# Generated by Django 3.1.4 on 2020-12-04 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sohayota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('email_id', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(choices=[('Job', 'Job'), ('Business', 'Business'), ('Retired', 'Retired'), ('Housewife', 'Housewife'), ('Student', 'Student'), ('Other', 'Other')], max_length=100, null=True)),
            ],
        ),
    ]
